# Generated by Django 2.1.1 on 2018-10-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181028_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='date_of_birth',
        ),
    ]
